version: '3.1'

services:
  harix-auto-test-oss-janus-build-base:
    image: harbor.cloudminds.com/hari/harix-auto-test-oss-janus-build-base:20201231
    volumes:
    - /home:/home
    command:
      - /bin/bash
      - -c
      - |
        sleep 10000
